<template>
  <header class="header-scene">
    <div class="sky">
      <div class="stars-small">&nbsp;</div>
      <div class="stars-large">&nbsp;</div>
      <div class="sun-wrapper">
        &nbsp;
        <div class="sun">&nbsp;</div>
      </div>
      <div class="city-scape">
        &nbsp;
        <div class="building xs">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building md">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building xxl">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building sm">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building lg">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building xs">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building xxl">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building sm">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building lg">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building xl">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building md">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building xl">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building lg">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
        <div class="building xs">
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
          <div class="window">&nbsp;</div>
        </div>
      </div>
    </div>
    <div class="foreground">
      <div class="line spacing xxs">&nbsp;</div>
      <div class="line spacing xs">&nbsp;</div>
      <div class="line spacing xs">&nbsp;</div>
      <div class="line spacing xs">&nbsp;</div>
      <div class="line spacing sm">&nbsp;</div>
      <div class="line spacing sm">&nbsp;</div>
      <div class="line spacing md">&nbsp;</div>
      <div class="line spacing md">&nbsp;</div>
      <div class="line spacing lg">&nbsp;</div>
      <div class="line spacing lg">&nbsp;</div>
      <div class="line spacing xl">&nbsp;</div>
      <div class="line spacing xl">&nbsp;</div>
      <div class="line">&nbsp;</div>
    </div>
  </header>
</template>

<script>
export default {}
</script>

<style></style>
